import type { InsightArticle } from "@/lib/insight-articles/types";

export const mexicoInsight: InsightArticle = {
  slug: "mexico",
  countryEn: "Mexico",
  countryPath: "/countries/mexico",
  kicker: "Strategic investment outlook",
  headline: ["墨西哥国家洞察：", "2026—2030战略投资与项目机会"],
  lede: "从国家投资主线拆到行业、区域和采购入口，帮你判断未来几年该跟踪什么，而不只追一条快截止的招标。",
  published: "2026-09-17",
  modified: "2026-10-05",
  stats: [
    { label: "五年投资基准", value: "约3,252亿", unit: "美元", detail: "原币5.6万亿墨西哥比索", note: "2026—2030年公共及混合投资" },
    { label: "项目储备", value: "1,500+", unit: "个基础设施项目", note: "已进入财务与技术分析" },
    { label: "三大领域占比", value: "83.72%", unit: "能源、铁路与公路", note: "资金最集中的三个方向" },
    { label: "战略行业", value: "8", unit: "个", note: "能源、交通、港口、医疗、水务等" },
  ],
  basis: "5.6万亿比索是2026年2月公布的五年基准，各行业金额按官方占比折算。专项计划口径不同，不能与总盘子相加；1,500多个项目也不等于都已公开招标。",
  overview: {
    title: "不是项目清单，而是一条投资主线",
    points: [
      { lead: "五年投入5.6万亿比索", text: "2026年在已批预算外再增7,220亿比索（约419亿美元），官方称约合GDP的2%。" },
      { lead: "混合投资不等于统一PPP", text: "可能是政府与私人资本、社会组织或专门投资工具的不同组合；法律结构和采购方式要到实施阶段逐项确认。" },
      { lead: "能源、铁路、公路占83.72%", text: "需求会从主合同延伸到输配电设备、轨道系统、钢结构、工程机械、检测和本地施工服务。" },
    ],
  },
  sectors: {
    title: "八个战略行业，资金高度集中",
    intro: "按官方行业占比乘以5.6万亿比索估算，只表示量级，不代表各行业已获同额预算。",
    shares: true,
    bars: [
      { name: "能源", value: 54.15, tag: "54.15%", amount: "约3.03万亿比索（约1,761亿美元）", color: "bg-[#f5a20b]" },
      { name: "铁路", value: 15.63, tag: "15.63%", amount: "约8,753亿比索（约508亿美元）", color: "bg-[#4e9ad4]" },
      { name: "公路", value: 13.94, tag: "13.94%", amount: "约7,806亿比索（约453亿美元）", color: "bg-[#6db8e8]" },
      { name: "港口", value: 6.48, tag: "6.48%", amount: "约3,629亿比索（约211亿美元）", color: "bg-[#e2702a]" },
      { name: "医疗卫生", value: 6.23, tag: "6.23%", amount: "约3,489亿比索（约203亿美元）", color: "bg-[#67a98d]" },
      { name: "水务", value: 2.83, tag: "2.83%", amount: "约1,585亿比索（约92亿美元）", color: "bg-[#5aa8ba]" },
      { name: "教育", value: 0.34, tag: "0.34%", amount: "约190亿比索（约11亿美元）", color: "bg-[#a58ac4]" },
      { name: "机场", value: 0.04, tag: "0.04%", amount: "约22亿比索（约1.3亿美元）", color: "bg-[#8998a1]" },
    ],
    takeaways: [
      { lead: "能源与交通先行", text: "三项合计83.72%，最先形成大额设备、工程和专业服务采购。" },
      { lead: "从单体项目到走廊", text: "港口、铁路、公路、电网和园区在同一地区叠加，机会沿产业带连续出现。" },
      { lead: "本地能力决定后续订单", text: "项目进入运营后，备件、维护、仓储和技术服务更依赖墨西哥本地团队。" },
    ],
  },
  pipeline: {
    title: "已经能看到的八个工程方向",
    items: [
      { icon: "energy", title: "能源与电网", figure: "接近32GW新增发电", text: "更新口径约7,400亿比索（约430亿美元）；输电另有81.77亿美元计划，含275条线路、524项变电站工程。" },
      { icon: "rail", title: "铁路", figure: "3,000+公里客运铁路", text: "2025—2030年覆盖墨西哥城—Pachuca、墨西哥城—Querétaro—Nuevo Laredo及北向Nogales走廊，并推进Tren Maya货运。" },
      { icon: "road", title: "公路与桥梁", figure: "6,478.32亿比索 · 11,366公里", text: "截至2026年9月（约376亿美元）：已完成1,796公里，在建4,223公里；Banobras另跟踪19个项目、约2,138.68亿比索。" },
      { icon: "port", title: "港口", figure: "9个重点港口", text: "公共投资551.79亿比索（约32亿美元）、私人投资2,410.51亿比索（约140亿美元）；疏浚、码头、装卸和集疏运同步释放需求。" },
      { icon: "water", title: "水务", figure: "17个战略项目", text: "截至2026年9月，另有约2.4万项饮用水与排水工程覆盖2,183个市镇；联邦、州、地方共同推进，采购入口分散。" },
      { icon: "industry", title: "产业发展极", figure: "首批15个，网络扩至26个", text: "首批分布在14个州，配套新固定资产100%加速扣除等激励；之后为15个全国加11个东南部发展极。" },
      { icon: "digital", title: "信息通信技术", figure: "Nube MX · 数据中心", text: "2026年重点：Aguascalientes与Tulancingo数据中心扩容、公共云GPU、Supercomputadora Coatlicue、骨干网与农村站点。" },
      { icon: "health", title: "医疗卫生", figure: "约200亿比索设备更新", text: "2026年三大公共医疗体系更新磁共振、病床、手术室等（约12亿美元）；国家卫生基础设施总体规划是项目登记入口。" },
    ],
  },
  regions: {
    title: "四类区域最值得持续跟踪",
    map: {
      src: "/insights/mexico-regions.svg",
      width: 1600,
      height: 1000,
      alt: "墨西哥重点区域地图，按省级行政区着色：1 北部边境与制造业带、2 中部与Bajío工业带、3 墨西哥湾与东南部、4 太平洋港口与物流走廊",
      caption: "按省级行政区着色，编号对应下方区域卡片，图标为该区域的重点方向；仅示意，不代表具体项目选线或投资金额的地域分布。",
    },
    items: [
      { color: "bg-[#f5a20b]", title: "北部边境与制造业带", places: "Sonora、Chihuahua、Coahuila、Nuevo León、Tamaulipas", focus: "电力扩容、跨境铁路公路、工业用水和物流园区；首批发展极含Hermosillo、San Jerónimo（Juárez）和Altamira。" },
      { color: "bg-[#82c8f2]", title: "中部与Bajío工业带", places: "Ciudad de México、Estado de México、Hidalgo、Querétaro、Guanajuato、San Luis Potosí、Jalisco、Puebla、Tlaxcala", focus: "客运铁路、干线公路、电网、工业园区和汽车制造供应链；连接首都圈与北部边境，工程叠加最多。" },
      { color: "bg-[#ef6b2e]", title: "墨西哥湾与东南部", places: "Veracruz、Tabasco、Campeche、Yucatán、Quintana Roo、Oaxaca、Chiapas", focus: "港口、石化与天然气、水务、Tren Maya货运化；CIIT把Coatzacoalcos、Salina Cruz、Dos Bocas与Puerto Chiapas连成一体。" },
      { color: "bg-[#4e9ad4]", title: "太平洋港口与物流走廊", places: "Baja California、Sinaloa、Colima、Michoacán、Guerrero", focus: "Ensenada、Manzanillo、Lázaro Cárdenas、Salina Cruz等港口扩建，加上集疏运公路、铁路和仓储。" },
    ],
    note: "同一地区连续出现多类工程，比单个超级项目更重要：能源、交通、港口和园区一起建，才有长期的设备供应、仓储、售后和分包需求。",
  },
  opportunities: {
    title: "中国企业可参与空间",
    intro: "规划规模不等于订单。按行业找潜在项目，盯住会发采购的主体。",
    items: [
      { sector: "能源", scope: ["发电", "储能", "输电线路", "变电站", "配电设备", "工程服务"], buyers: "CFE、SENER、CENACE及项目主体" },
      { sector: "铁路", scope: ["轨道", "桥隧", "信号通信", "车辆", "站房", "施工设备与运维"], buyers: "SICT、铁路主管机构及专项项目公司" },
      { sector: "公路与桥梁", scope: ["EPC", "钢结构", "桩基", "路面", "交通安全设备", "机械与材料"], buyers: "SICT、CAPUFE、州政府及特许经营项目" },
      { sector: "港口与物流", scope: ["疏浚", "码头", "堆场", "装卸设备", "仓储", "集疏运"], buyers: "SEMAR、各港口ASIPONA及码头运营商" },
      { sector: "水务", scope: ["输水", "处理", "泵站", "管网", "防洪", "节水灌溉", "监测"], buyers: "CONAGUA、州及市级水务机构" },
      { sector: "工业园区", scope: ["园区基础设施", "电力与水务配套", "厂房", "物流与运营"], buyers: "经济部、州政府、发展极运营主体及入园企业" },
      { sector: "信息通信技术", scope: ["数据中心", "云平台", "通信网络", "网络安全", "智慧城市", "政务系统"], buyers: "ATDT、CRT、CFE Telecom及公共机构" },
      { sector: "医疗卫生", scope: ["医疗设备", "影像诊断", "实验室", "医院信息化", "耗材与维保"], buyers: "卫生部、IMSS、ISSSTE、IMSS-Bienestar及州级卫生机构" },
    ],
  },
  entry: {
    title: "把国家机会变成可执行动作",
    steps: [
      { title: "先选行业和区域", detail: "选两三个最匹配的细分领域，锁定重点州、主管机构和当地总包。" },
      { title: "分清规划和招标", detail: "宣布投资不等于开放采购；跟踪预算、可研、环评、正式公告和更正。" },
      { title: "备好履约条件", detail: "墨西哥法人、SAT电子签名、税务社保、本地成分、西语文件，逐项目核对。" },
      { title: "留出合作空间", detail: "直接投标门槛高时，做联合体、设备供应、专业分包或售后伙伴。" },
      { title: "建连续跟踪表", detail: "记下主管机构、阶段、预算、采购入口、预计时间和下次核验点。" },
    ],
    guides: [
      { href: "/guides/mexico-compras-mx", label: "查看Compras MX参标指南" },
      { href: "/guides", label: "全部参标指南" },
    ],
  },
  sources: {
    intro: "优先采用墨西哥总统府、财政部、SICT、CONAGUA、SEMAR及Proyectos México公开资料。金额和项目状态会变化，参与前请回到原文件核对。",
    items: [
      { label: "墨西哥总统府：2026—2030基础设施投资计划", href: "https://www.gob.mx/presidencia/prensa/el-plan-de-inversion-en-infraestructura-para-el-desarrollo-con-bienestar-contempla-en-2026-2-adicional-del-pib-y-5-6-bdp-al-2030?idiom=es-MX", note: "5.6万亿比索基准、2026年新增7,220亿比索与八个战略行业。" },
      { label: "墨西哥财政部：基础设施投资计划演示文件", href: "https://www.finanzaspublicas.hacienda.gob.mx/work/models/Finanzas_Publicas/docs/ori/Ingles/Guides/Plan_de_Inversion_en_Infraestructura_2026-2030.pdf", note: "各行业投资占比的原始图表。" },
      { label: "Proyectos México：在墨西哥投资基础设施", href: "https://www.proyectosmexico.gob.mx/como-invertir-en-infraestructura-en-mexico/", note: "超过1,500个项目、投资机制和项目入口。" },
      { label: "墨西哥总统府：首批15个经济发展极", href: "https://www.gob.mx/presidencia/prensa/plan-mexico-presidenta-claudia-sheinbaum-pone-en-marcha-los-primeros-15-polos-de-desarrollo-economico-para-el-bienestar-en-14-estados?idiom=es-MX", note: "发展极分布、行业方向与激励措施。" },
      { label: "墨西哥总统府：Plan México与26个发展极网络", href: "https://www.gob.mx/presidencia/prensa/presidenta-claudia-sheinbaum-presenta-plan-mexico-a-miembros-del-foro-economico-mundial?idiom=en", note: "15个全国发展极与11个东南部发展极。" },
      { label: "墨西哥总统府：CFE输电扩建计划", href: "https://www.gob.mx/presidencia/prensa/cfe-invertira-8-mil-177-mdd-para-fortalecer-red-de-transmision-en-beneficio-de-50-millones-de-mexicanas-y-mexicanos?idiom=es-MX", note: "275条输电线路、524项变电站工程、81.77亿美元。" },
      { label: "SICT：2025—2030铁路发展目标", href: "https://www.gob.mx/sict/prensa/construir-3-mil-km-de-trenes-de-pasajeros-objetivo-de-movilidad-para-la-sict-en-2025-2030", note: "超过3,000公里客运铁路与主要走廊。" },
      { label: "SICT：公路与桥梁投资计划", href: "https://www.gob.mx/presidencia/prensa/mejor-comunicacion-es-desarrollo-y-bienestar-presidenta-avanza-programa-de-infraestructura-carretera-con-inversion-de-647-mil-832-mdp", note: "截至2026年9月的6,478.32亿比索、11,366公里与进度。" },
      { label: "墨西哥总统府：九个港口重点工程", href: "https://www.gob.mx/presidencia/prensa/mexico-sera-potencia-regional-portuaria", note: "公共和私人港口投资及重点港口。" },
      { label: "CONAGUA：国家水务战略项目", href: "https://www.gob.mx/conagua/prensa/el-gobierno-de-mexico-desarrolla-obras-estrategicas-para-mejorar-los-servicios-de-agua-drenaje-y-saneamiento-para-el-bienestar-del-pueblo?idiom=es", note: "17个战略项目、约2.4万项水务工程。" },
      { label: "Proyectos México：跨洋走廊CIIT", href: "https://www.proyectosmexico.gob.mx/ppp03-ciit/", note: "Veracruz、Oaxaca、Tabasco与Chiapas的港口、铁路和发展极。" },
      { label: "ATDT：2026数字基础设施议程", href: "https://www.gob.mx/atdt/agendas/2030/infraestructura-digital", note: "Nube MX、公共数据中心与Supercomputadora Coatlicue。" },
      { label: "墨西哥总统府：公共医疗设备更新", href: "https://www.gob.mx/presidencia/prensa/se-invierten-20-mil-mdp-en-el-salto-tecnologico-en-el-imss-issste-e-imss-bienestar-presidenta-claudia-sheinbaum?idiom=es", note: "2026年约200亿比索医疗设备投资。" },
      { label: "墨西哥央行：FIX汇率", href: "https://www.banxico.org.mx/tipcamb/tipCamMIAction.do?idioma=sp", note: "2026年9月21日：1美元＝17.2203墨西哥比索。" },
    ],
    fx: "按墨西哥央行2026年9月21日FIX汇率1美元＝17.2203墨西哥比索换算并取整，仅用于理解量级，不构成报价或财务依据。",
  },
};
