import type { Locale, LocalizedText } from "@/types/tender";

export function localize(value: LocalizedText, locale: Locale): string {
  return value[locale];
}

export const uiText = {
  tagline: {
    en: "Discover. Understand. Qualify.",
    es: "Descubre. Comprende. Califica.",
    zh: "发现·理解·资格判断",
  },
  heroTitle: {
    en: "Tender intelligence for companies expanding into Mexico",
    es: "Inteligencia de licitaciones para proveedores internacionales en México",
    zh: "中国企业出海墨西哥的拉美招投标平台",
  },
  heroSubtitle: {
    en: "Break through the Spanish-language barrier: understand Mexican government tender requirements in your own language, and decide bid or no-bid with confidence.",
    es: "Licitaciones del gobierno mexicano, traducidas y estructuradas para que proveedores internacionales entiendan los requisitos de calificación en minutos y decidan si participar con confianza.",
    zh: "看不懂西语标书、搞不清资质要求？我们把墨西哥政府招标信息转化为结构化的中文情报，帮您快速判断能不能投、该不该投。",
  },
  browseTenders: {
    en: "Browse Tenders",
    es: "Ver Licitaciones",
    zh: "浏览招标",
  },
  featuredTenders: {
    en: "Recently Published",
    es: "Publicadas Recientemente",
    zh: "近期发布",
  },
  navHome: { en: "Home", es: "Inicio", zh: "首页" },
  navTenders: { en: "Tenders", es: "Licitaciones", zh: "招标项目" },
  searchPlaceholder: {
    en: "Search by issuing agency or project keyword…",
    es: "Buscar por entidad emisora o palabra clave del proyecto…",
    zh: "按发标单位、项目关键字搜索…",
  },
  industryLabel: { en: "Industry", es: "Industria", zh: "行业" },
  industryMatchAll: {
    en: "Require all selected industries (e.g. ICT + Power)",
    es: "Requerir todas las industrias seleccionadas (ej. TIC + Electricidad)",
    zh: "仅显示同时符合所选全部行业的项目（如：ICT + 电力）",
  },
  scopeLabel: { en: "Scope", es: "Alcance", zh: "标的类型" },
  statusLabel: { en: "Status", es: "Estado", zh: "状态" },
  allIndustries: { en: "All Industries", es: "Todas las Industrias", zh: "全部行业" },
  allScopes: { en: "All Scopes", es: "Todos los Alcances", zh: "全部类型" },
  allStatuses: { en: "All Statuses", es: "Todos los Estados", zh: "全部状态" },
  clearFilters: { en: "Clear filters", es: "Limpiar filtros", zh: "清除筛选" },
  resultsCount: {
    en: "tenders found",
    es: "licitaciones encontradas",
    zh: "条招标结果",
  },
  noResults: {
    en: "No tenders match your filters.",
    es: "Ninguna licitación coincide con tus filtros.",
    zh: "没有符合筛选条件的招标。",
  },
  estimatedValue: { en: "Estimated Value", es: "Valor Estimado", zh: "预估金额" },
  awardedToLabel: { en: "Awarded To", es: "Adjudicado A", zh: "中标供应商" },
  awardedValueLabel: { en: "Awarded Value", es: "Valor Adjudicado", zh: "中标金额" },
  awardDateLabel: { en: "Award Date", es: "Fecha de Adjudicación", zh: "中标日期" },
  submissionDeadline: {
    en: "Submission Deadline",
    es: "Fecha Límite de Presentación",
    zh: "提交截止日期",
  },
  viewDetails: { en: "View Details", es: "Ver Detalles", zh: "查看详情" },
  backToTenders: { en: "Back to Tenders", es: "Volver a Licitaciones", zh: "返回招标列表" },
  notFoundTitle: { en: "Tender not found", es: "Licitación no encontrada", zh: "未找到该招标" },
  notFoundBody: {
    en: "This tender may have been removed or the link is incorrect.",
    es: "Es posible que esta licitación haya sido eliminada o que el enlace sea incorrecto.",
    zh: "该招标可能已被移除，或链接有误。",
  },
  overview: { en: "Overview", es: "Resumen", zh: "概览" },
  buyer: { en: "Buyer", es: "Comprador", zh: "采购人" },
  buyerLabelCard: { en: "Issuing Agency", es: "Entidad Emisora", zh: "发标单位" },
  governmentLevelLabel: { en: "Government Level", es: "Nivel de Gobierno", zh: "政府层级" },
  procedureType: { en: "Procedure Type", es: "Tipo de Procedimiento", zh: "采购方式" },
  participationScopeLabel: { en: "Bidder Eligibility", es: "Carácter del Procedimiento", zh: "参与资格范围" },
  locationLabel: { en: "Location", es: "Ubicación", zh: "地点" },
  publicationDateLabel: { en: "Publication Date", es: "Fecha de Publicación", zh: "发布日期" },
  /** Used instead of publicationDateLabel when Tender.publicationDateIsEstimated is true — the stored date is when this platform first ingested the tender, not a real government-published date (some sources' export files carry no publication-date column at all — see types/tender.ts). */
  ingestedDateLabel: { en: "Date Added", es: "Fecha de Registro", zh: "收录日期" },
  qualifications: { en: "Qualification Requirements", es: "Requisitos de Calificación", zh: "资质要求" },
  experienceRequirements: { en: "Experience Requirements", es: "Requisitos de Experiencia", zh: "经验要求" },
  requiredDocuments: { en: "Required Documents", es: "Documentos Requeridos", zh: "所需文件" },
  criticalDates: { en: "Critical Dates", es: "Fechas Críticas", zh: "关键日期" },
  risks: { en: "Risks", es: "Riesgos", zh: "风险提示" },
  source: { en: "Source", es: "Fuente", zh: "来源" },
  mandatory: { en: "Mandatory", es: "Obligatorio", zh: "强制要求" },
  optional: { en: "Optional", es: "Opcional", zh: "非强制" },
  viewSourceDocument: { en: "View source document", es: "Ver documento fuente", zh: "查看原始来源文件" },
  copyProcedureNumber: { en: "Copy procedure number", es: "Copiar número de procedimiento", zh: "复制招标编号" },
  copiedToClipboard: { en: "Copied", es: "Copiado", zh: "已复制" },
  noneListed: { en: "None listed for this tender.", es: "No se enlistan para esta licitación.", zh: "本项目未列出相关内容。" },

  navSaved: { en: "Saved", es: "Guardados", zh: "我的收藏" },
  saveTender: { en: "Save tender", es: "Guardar licitación", zh: "收藏该招标" },
  unsaveTender: { en: "Remove from saved", es: "Quitar de guardados", zh: "取消收藏" },
  savedTenders: { en: "Saved Tenders", es: "Licitaciones Guardadas", zh: "已收藏的招标" },
  savedSearches: { en: "Saved Searches", es: "Búsquedas Guardadas", zh: "已保存的搜索" },
  noSavedTenders: {
    en: "You haven't saved any tenders yet.",
    es: "Aún no has guardado ninguna licitación.",
    zh: "您还没有收藏任何招标。",
  },
  noSavedSearches: {
    en: "You haven't saved any searches yet.",
    es: "Aún no has guardado ninguna búsqueda.",
    zh: "您还没有保存任何搜索。",
  },
  saveThisSearch: { en: "Save this search", es: "Guardar esta búsqueda", zh: "保存当前搜索" },
  searchNamePlaceholder: {
    en: "Name this search…",
    es: "Nombra esta búsqueda…",
    zh: "为该搜索命名…",
  },
  notifyMeOfNewMatches: {
    en: "Notify me about new matching tenders",
    es: "Notificarme sobre nuevas licitaciones coincidentes",
    zh: "有新匹配招标时通知我",
  },
  alertNotYetDeliveredNote: {
    en: "You'll see these as in-app notifications (bell icon in the header) — email delivery isn't available yet.",
    es: "Las verás como notificaciones dentro de la app (ícono de campana) — el envío por correo aún no está disponible.",
    zh: "这些提醒会显示为站内通知（页头铃铛图标）——邮件通知功能尚未上线。",
  },
  login: { en: "Log in", es: "Iniciar sesión", zh: "登录" },
  register: { en: "Register", es: "Registrarse", zh: "注册" },
  logout: { en: "Log out", es: "Cerrar sesión", zh: "退出登录" },
  emailLabel: { en: "Email", es: "Correo electrónico", zh: "邮箱" },
  passwordLabel: { en: "Password", es: "Contraseña", zh: "密码" },
  createAccount: { en: "Create account", es: "Crear cuenta", zh: "创建账户" },
  signIn: { en: "Sign in", es: "Iniciar sesión", zh: "登录" },
  alreadyHaveAccount: { en: "Already have an account?", es: "¿Ya tienes una cuenta?", zh: "已有账户？" },
  dontHaveAccount: { en: "Don't have an account?", es: "¿No tienes una cuenta?", zh: "还没有账户？" },
  checkYourEmail: { en: "Check your email", es: "Revisa tu correo", zh: "请查收邮箱" },
  checkYourEmailBody: {
    en: "We sent a confirmation link to your email. Click it to activate your account, then log in.",
    es: "Enviamos un enlace de confirmación a tu correo. Haz clic en él para activar tu cuenta y luego inicia sesión.",
    zh: "我们已向您的邮箱发送了确认链接。点击链接激活账户后即可登录。",
  },
  passwordTab: { en: "Password", es: "Contraseña", zh: "密码登录" },
  magicLinkTab: { en: "Magic Link", es: "Enlace Mágico", zh: "免密登录" },
  sendMagicLink: { en: "Send magic link", es: "Enviar enlace mágico", zh: "发送登录链接" },
  magicLinkSent: { en: "Check your email", es: "Revisa tu correo", zh: "请查收邮箱" },
  magicLinkSentBody: {
    en: "We sent a one-click login link to your email. It expires shortly, so use it soon.",
    es: "Enviamos un enlace de acceso de un clic a tu correo. Caduca pronto, así que úsalo cuanto antes.",
    zh: "我们已向您的邮箱发送了一键登录链接，链接很快会过期，请尽快使用。",
  },
  authNotConfigured: {
    en: "Accounts aren't available yet — the site owner hasn't connected authentication.",
    es: "Las cuentas aún no están disponibles — el propietario del sitio no ha configurado la autenticación.",
    zh: "账户功能尚未开通——网站尚未配置登录认证。",
  },
  notifications: { en: "Notifications", es: "Notificaciones", zh: "通知" },
  noNotifications: {
    en: "No new notifications. Enable alerts on a saved search to get notified here.",
    es: "No hay notificaciones nuevas. Activa alertas en una búsqueda guardada para recibir avisos aquí.",
    zh: "暂无新通知。在已保存的搜索中开启提醒，即可在此收到通知。",
  },
  markAllRead: { en: "Mark all as read", es: "Marcar todo como leído", zh: "全部标记为已读" },
  matchedSearch: { en: "Matched", es: "Coincide con", zh: "匹配自" },
  save: { en: "Save", es: "Guardar", zh: "保存" },
  cancel: { en: "Cancel", es: "Cancelar", zh: "取消" },
  remove: { en: "Remove", es: "Quitar", zh: "移除" },
  alertEnabled: { en: "Alert on", es: "Alerta activada", zh: "提醒已开启" },
  sortLabel: { en: "Sort", es: "Ordenar", zh: "排序" },
  sortPublicationDesc: { en: "Newest", es: "Más recientes", zh: "最新发布" },
  sortDeadlineAsc: { en: "Deadline: Soonest", es: "Fecha límite: Próxima", zh: "截止日期：最近优先" },
  previousPage: { en: "Previous", es: "Anterior", zh: "上一页" },
  nextPage: { en: "Next", es: "Siguiente", zh: "下一页" },
  pageOf: { en: "Page {page} of {total}", es: "Página {page} de {total}", zh: "第 {page} 页，共 {total} 页" },

  navPricing: { en: "Pricing", es: "Precios", zh: "订阅服务" },
  navAccount: { en: "Account", es: "Cuenta", zh: "账户" },
  account: { en: "Account", es: "Cuenta", zh: "账户" },
  companyNameLabel: { en: "Company name", es: "Nombre de la empresa", zh: "公司名称" },
  saveProfile: { en: "Save", es: "Guardar", zh: "保存" },
  profileSaved: { en: "Saved", es: "Guardado", zh: "已保存" },
  currentPlan: { en: "Current plan", es: "Plan actual", zh: "当前套餐" },
  freePlan: { en: "Free preview — no active subscription", es: "Vista previa gratuita — sin suscripción activa", zh: "免费预览——尚未订阅付费套餐" },
  viewPlans: { en: "View plans", es: "Ver planes", zh: "查看套餐" },
  pricingTitle: { en: "Plans for every stage of bidding", es: "Planes para cada etapa de licitación", zh: "适配各阶段投标需求的套餐" },
  pricingSubtitle: {
    en: "Start free-preview, upgrade as your team starts bidding seriously.",
    es: "Comienza con la vista previa gratuita y mejora conforme tu equipo empiece a licitar en serio.",
    zh: "从免费预览开始，随着团队正式投标逐步升级。",
  },
  mostPopular: { en: "Most popular", es: "Más popular", zh: "最受欢迎" },
  paymentNotConfigured: {
    en: "Checkout isn't connected yet — this is a preview of the plans. Contact us to get set up.",
    es: "El pago aún no está configurado — esta es una vista previa de los planes. Contáctanos para activarlo.",
    zh: "支付功能尚未开通——这里仅为套餐预览。请联系我们完成开通。",
  },
  scaleLabel: { en: "Scale", es: "Escala", zh: "项目规模" },
  countryLabel: { en: "Country", es: "País", zh: "国家" },

  documentsNeededTitle: {
    en: "Tenders needing attachments",
    es: "Licitaciones que necesitan anexos",
    zh: "待下载附件的标书",
  },
  documentsNeededSubtitle: {
    en: "Tenders that passed relevance screening but have no attachments on file yet — click the source link to open the real tender page and download the documents by hand.",
    es: "Licitaciones que pasaron el filtro de relevancia pero aún no tienen anexos registrados — haz clic en el enlace de origen para abrir la página real y descargar los documentos manualmente.",
    zh: "以下标书已通过筛选（黑白名单），但还没有录入任何附件——点击来源链接打开真实标书页面，手动下载附件。",
  },
  documentsNeededEmpty: {
    en: "Nothing needs attachments right now — every screened tender already has documents on file.",
    es: "Por ahora nada necesita anexos — todas las licitaciones filtradas ya tienen documentos registrados.",
    zh: "暂无待处理项目——所有通过筛选的标书都已经录入了附件。",
  },
  colTitle: { en: "Title", es: "Título", zh: "标题" },
  colValueTier: { en: "Value tier", es: "Nivel de valor", zh: "金额档" },
  colTenderId: { en: "Tender ID", es: "ID de la licitación", zh: "标书ID" },
  colPublicationDate: { en: "Published", es: "Publicada", zh: "发标日期" },
  colSourceLink: { en: "Source", es: "Origen", zh: "来源链接" },
  openSource: { en: "Open source page", es: "Abrir página de origen", zh: "打开来源页面" },
} satisfies Record<string, LocalizedText>;
