import type { Locale, LocalizedText } from "@/types/tender";

export function localize(value: LocalizedText, locale: Locale): string {
  return value[locale];
}

export const uiText = {
  tagline: {
    en: "Discover. Understand. Qualify.",
    es: "Descubre. Comprende. Califica.",
    zh: "发现·理解·资格判断",
  },
  heroTitle: {
    en: "Tender intelligence for teams that bid to win",
    es: "Inteligencia de licitaciones para equipos que buscan ganar",
    zh: "为志在中标的团队提供招投标情报",
  },
  heroSubtitle: {
    en: "Search Mexican government tenders, understand qualification requirements in minutes, and decide bid or no-bid with confidence.",
    es: "Busca licitaciones del gobierno mexicano, comprende los requisitos de calificación en minutos y decide si participar con confianza.",
    zh: "检索墨西哥政府招标信息，几分钟内理解资格要求，自信地判断是否值得投标。",
  },
  browseTenders: {
    en: "Browse Tenders",
    es: "Ver Licitaciones",
    zh: "浏览招标",
  },
  featuredTenders: {
    en: "Recently Published",
    es: "Publicadas Recientemente",
    zh: "近期发布",
  },
  navHome: { en: "Home", es: "Inicio", zh: "首页" },
  navTenders: { en: "Tenders", es: "Licitaciones", zh: "招标" },
  searchPlaceholder: {
    en: "Search by tender name, buyer, or ID…",
    es: "Buscar por nombre, comprador o ID…",
    zh: "按名称、采购人或编号搜索…",
  },
  industryLabel: { en: "Industry", es: "Industria", zh: "行业" },
  scopeLabel: { en: "Scope", es: "Alcance", zh: "标的类型" },
  statusLabel: { en: "Status", es: "Estado", zh: "状态" },
  allIndustries: { en: "All Industries", es: "Todas las Industrias", zh: "全部行业" },
  allScopes: { en: "All Scopes", es: "Todos los Alcances", zh: "全部类型" },
  allStatuses: { en: "All Statuses", es: "Todos los Estados", zh: "全部状态" },
  clearFilters: { en: "Clear filters", es: "Limpiar filtros", zh: "清除筛选" },
  resultsCount: {
    en: "tenders found",
    es: "licitaciones encontradas",
    zh: "条招标结果",
  },
  noResults: {
    en: "No tenders match your filters.",
    es: "Ninguna licitación coincide con tus filtros.",
    zh: "没有符合筛选条件的招标。",
  },
  estimatedValue: { en: "Estimated Value", es: "Valor Estimado", zh: "预估金额" },
  submissionDeadline: {
    en: "Submission Deadline",
    es: "Fecha Límite de Presentación",
    zh: "提交截止日期",
  },
  viewDetails: { en: "View Details", es: "Ver Detalles", zh: "查看详情" },
  backToTenders: { en: "Back to Tenders", es: "Volver a Licitaciones", zh: "返回招标列表" },
  notFoundTitle: { en: "Tender not found", es: "Licitación no encontrada", zh: "未找到该招标" },
  notFoundBody: {
    en: "This tender may have been removed or the link is incorrect.",
    es: "Es posible que esta licitación haya sido eliminada o que el enlace sea incorrecto.",
    zh: "该招标可能已被移除，或链接有误。",
  },
  overview: { en: "Overview", es: "Resumen", zh: "概览" },
  buyer: { en: "Buyer", es: "Comprador", zh: "采购人" },
  governmentLevelLabel: { en: "Government Level", es: "Nivel de Gobierno", zh: "政府层级" },
  procedureType: { en: "Procedure Type", es: "Tipo de Procedimiento", zh: "采购方式" },
  locationLabel: { en: "Location", es: "Ubicación", zh: "地点" },
  publicationDateLabel: { en: "Publication Date", es: "Fecha de Publicación", zh: "发布日期" },
  qualifications: { en: "Qualification Requirements", es: "Requisitos de Calificación", zh: "资质要求" },
  experienceRequirements: { en: "Experience Requirements", es: "Requisitos de Experiencia", zh: "经验要求" },
  requiredDocuments: { en: "Required Documents", es: "Documentos Requeridos", zh: "所需文件" },
  criticalDates: { en: "Critical Dates", es: "Fechas Críticas", zh: "关键日期" },
  risks: { en: "Risks", es: "Riesgos", zh: "风险提示" },
  source: { en: "Source", es: "Fuente", zh: "来源" },
  mandatory: { en: "Mandatory", es: "Obligatorio", zh: "强制要求" },
  optional: { en: "Optional", es: "Opcional", zh: "非强制" },
  viewSourceDocument: { en: "View source document", es: "Ver documento fuente", zh: "查看原始来源文件" },
  noneListed: { en: "None listed for this tender.", es: "No se enlistan para esta licitación.", zh: "本项目未列出相关内容。" },

  navSaved: { en: "Saved", es: "Guardados", zh: "已收藏" },
  saveTender: { en: "Save tender", es: "Guardar licitación", zh: "收藏该招标" },
  unsaveTender: { en: "Remove from saved", es: "Quitar de guardados", zh: "取消收藏" },
  savedTenders: { en: "Saved Tenders", es: "Licitaciones Guardadas", zh: "已收藏的招标" },
  savedSearches: { en: "Saved Searches", es: "Búsquedas Guardadas", zh: "已保存的搜索" },
  noSavedTenders: {
    en: "You haven't saved any tenders yet.",
    es: "Aún no has guardado ninguna licitación.",
    zh: "您还没有收藏任何招标。",
  },
  noSavedSearches: {
    en: "You haven't saved any searches yet.",
    es: "Aún no has guardado ninguna búsqueda.",
    zh: "您还没有保存任何搜索。",
  },
  saveThisSearch: { en: "Save this search", es: "Guardar esta búsqueda", zh: "保存当前搜索" },
  searchNamePlaceholder: {
    en: "Name this search…",
    es: "Nombra esta búsqueda…",
    zh: "为该搜索命名…",
  },
  notifyMeOfNewMatches: {
    en: "Notify me about new matching tenders",
    es: "Notificarme sobre nuevas licitaciones coincidentes",
    zh: "有新匹配招标时通知我",
  },
  alertNotYetDeliveredNote: {
    en: "You'll see these as in-app notifications (bell icon in the header) — email delivery isn't available yet.",
    es: "Las verás como notificaciones dentro de la app (ícono de campana) — el envío por correo aún no está disponible.",
    zh: "这些提醒会显示为站内通知（页头铃铛图标）——邮件通知功能尚未上线。",
  },
  notifications: { en: "Notifications", es: "Notificaciones", zh: "通知" },
  noNotifications: {
    en: "No new notifications. Enable alerts on a saved search to get notified here.",
    es: "No hay notificaciones nuevas. Activa alertas en una búsqueda guardada para recibir avisos aquí.",
    zh: "暂无新通知。在已保存的搜索中开启提醒，即可在此收到通知。",
  },
  markAllRead: { en: "Mark all as read", es: "Marcar todo como leído", zh: "全部标记为已读" },
  matchedSearch: { en: "Matched", es: "Coincide con", zh: "匹配自" },
  save: { en: "Save", es: "Guardar", zh: "保存" },
  cancel: { en: "Cancel", es: "Cancelar", zh: "取消" },
  remove: { en: "Remove", es: "Quitar", zh: "移除" },
  alertEnabled: { en: "Alert on", es: "Alerta activada", zh: "提醒已开启" },
  sortLabel: { en: "Sort", es: "Ordenar", zh: "排序" },
  sortPublicationDesc: { en: "Newest", es: "Más recientes", zh: "最新发布" },
  sortDeadlineAsc: { en: "Deadline: Soonest", es: "Fecha límite: Próxima", zh: "截止日期：最近优先" },
  sortValueDesc: { en: "Value: High to Low", es: "Valor: Mayor a menor", zh: "金额：从高到低" },
  sortValueAsc: { en: "Value: Low to High", es: "Valor: Menor a mayor", zh: "金额：从低到高" },
  previousPage: { en: "Previous", es: "Anterior", zh: "上一页" },
  nextPage: { en: "Next", es: "Siguiente", zh: "下一页" },
  pageOf: { en: "Page {page} of {total}", es: "Página {page} de {total}", zh: "第 {page} 页，共 {total} 页" },
} satisfies Record<string, LocalizedText>;
