import { publicSummaryProblems, publicTitleProblems } from "@/lib/public-title";

/**
 * The rules for hand-editing the two columns the model writes for visitors —
 * `title_zh_public` and `summary_zh_public` (migrations 0053 and 0054).
 *
 * Extracted from the admin route so they can be tested, the same reason
 * lib/admin/form-merge.ts exists: one of them is a pin/unpin rule whose
 * failure mode is silent and only visible on the public site, days later.
 *
 * WHY AN ADMIN NEEDS TO EDIT THESE AT ALL
 *
 * lib/ingestion/generate-public-titles.ts validates every generated string
 * before storing it, but a validator only catches what a regex can be sure
 * of: Latin script, masking characters, procurement numbers, length. It
 * cannot catch a title that is clean, publishable and simply WRONG about the
 * project — 医疗设备采购 for a hospital construction works notice. Until now
 * there was no way to fix one: the column was absent from the admin form, so
 * the only remedy was re-running the generator and hoping the model changed
 * its mind.
 *
 * WHAT IS DELIBERATELY *NOT* HERE
 *
 * `title_zh_short` is generated by the same call and pinned by the same
 * mechanism, but it is the MEMBER title — it is supposed to keep the original
 * name, its validator needs the source text as a second argument, and no one
 * has reported a bad one. Adding a field nobody asked for to a form this size
 * costs more than it returns; when a bad short title does turn up, this module
 * is where it goes.
 */
export const ADMIN_EDITABLE_GENERATED_COLUMNS = ["title_zh_public", "summary_zh_public"] as const;

export type AdminEditableGeneratedColumn = (typeof ADMIN_EDITABLE_GENERATED_COLUMNS)[number];

export const GENERATED_COLUMN_LABELS: Record<AdminEditableGeneratedColumn, string> = {
  title_zh_public: "访客标题",
  summary_zh_public: "访客摘要",
};

/**
 * Why this hand-written value may not be published, or [] if it may.
 *
 * The SAME validators the generator's write path runs, deliberately. A
 * hand-written value that skipped them would be a second standard for one
 * column, and the one that skips the check is the one typed at 11pm — while
 * the rules here are not style preferences but the whole reason the column
 * exists (no original name, no procurement number, no masking artefacts).
 *
 * An empty value is not a problem, it is a release — see
 * releaseClearedGeneratedText below.
 */
export function generatedTextProblems(column: AdminEditableGeneratedColumn, value: string | null | undefined): string[] {
  const text = (value ?? "").trim();
  if (text === "") return [];
  return column === "title_zh_public" ? publicTitleProblems(text) : publicSummaryProblems(text);
}

/** Every problem across both columns, labelled, ready for a 400 body or a form hint. */
export function generatedTextRefusals(submitted: Partial<Record<AdminEditableGeneratedColumn, string | null>>): string[] {
  return ADMIN_EDITABLE_GENERATED_COLUMNS.flatMap((column) => {
    const problems = generatedTextProblems(column, submitted[column]);
    return problems.length === 0 ? [] : [`${GENERATED_COLUMN_LABELS[column]}：${problems.join("；")}`];
  });
}

/**
 * Drops the pin from a generated column the admin CLEARED.
 *
 * Run after the admin route's usual diff, and it is the one place these
 * columns depart from that diff's additive-only rule. The reason is a trap
 * the obvious implementation walks straight into:
 *
 * Clearing the field is a real edit, so the diff records it in
 * manual_field_overrides — and columnsToFill() in generate-public-titles.ts
 * skips every pinned column. The row would therefore sit with an EMPTY,
 * PERMANENTLY PINNED public title that the generator is forbidden to refill,
 * and publicTitleOf() falls back to `title.zh` — the administrative title,
 * carrying the Spanish project name, published to every visitor and every
 * crawler. An admin deleting a bad public title would have caused exactly the
 * leak the column was built to prevent, silently, with the page still looking
 * fine.
 *
 * So an empty value means "I have nothing better; hand it back to the
 * generator", which is also what an admin would expect clearing a generated
 * field to do. Writing one means "mine, keep it" — that path is left to the
 * diff, so merely opening the form and pressing save does not pin every
 * public title an admin has ever looked at.
 */
export function releaseClearedGeneratedText(
  overrides: readonly string[],
  submitted: Partial<Record<AdminEditableGeneratedColumn, string | null>>,
): string[] {
  const next = new Set(overrides);
  for (const column of ADMIN_EDITABLE_GENERATED_COLUMNS) {
    if ((submitted[column] ?? "").trim() === "") next.delete(column);
  }
  return [...next].sort();
}
