-- A single Chinese sentence (<=30 characters) answering "what is this
-- tender, in one line" — explicit user request (2026-09-06): generated by
-- Layer 2 document analysis (lib/ingestion/extract-requirements.ts)
-- alongside qualifications/experienceRequirements/requiredDocuments/risks,
-- shown on the public tender page directly above 资质要求. Distinct from
-- the existing `summary` column (a longer, source-derived paraphrase);
-- also admin-editable from the tender edit form like `summary` is.

alter table tenders
  add column if not exists one_line_summary text;
