-- A second Chinese title, written to be published rather than to be accurate.
--
-- The problem this solves is created by our own translation prompt, and is
-- worth stating plainly because the prompt is RIGHT to do it. Since
-- translate-titles-qwen.ts was written, a translated title carries the source
-- name in full-width parentheses after every transliterated place, facility
-- or project name: 马塔德罗（Matadero）泵站, 韦曼吉约（Huimanguillo）. The
-- reason given there still holds — "this name is the one thing in a title a
-- bidder must match against a map and against the bid documents, and a
-- transliteration on its own appears in neither".
--
-- But that makes title.zh the single best search key back to the official
-- notice that exists anywhere on this platform: it is the original Spanish or
-- Portuguese proper noun, sitting inside the Chinese text, ready to paste
-- into a search engine. A reader who does that reaches the source portal and
-- has no remaining reason to subscribe (user, 2026-09-19: 大多时候可以直接
-- 找到对应的投标入口，这样完全不需要订阅我们).
--
-- So the fix is not to weaken the translation. It is to keep title.zh exactly
-- as it is for members, and publish a different string to everyone else —
-- generated once at ingestion time by lib/ingestion/generate-public-titles.ts,
-- stored here, and used by every guest-facing projection.
--
-- What the public title keeps is what the page is actually meant to rank for:
-- the country, the industry, the kind of works and the asset. What it drops
-- is what identifies the row: municipalities, districts, rivers, facilities,
-- agency names, procurement codes and their Latin-script parentheses. Nobody
-- searches 瓜纳华托州莱昂市第三环路 by name unless they already know the
-- project; everybody searches 墨西哥 变电站 招标.
--
-- Nullable, and read through a fallback to title.zh (lib/public-title.ts), so
-- this column improves rows as it is populated instead of blanking every page
-- until a backfill finishes.
alter table tenders add column if not exists title_zh_public text;

comment on column tenders.title_zh_public is
  'De-identified Chinese title for guests, crawlers and search snippets: country + industry + works type, with place names, agency names, procurement codes and Latin-script parentheses removed. NULL means not generated yet — public surfaces fall back to title->>''zh''. Members always see title->>''zh''. Generated by npm run titles:public; never hand-written unless title_zh_public is also added to manual_field_overrides.';
