-- Two more generated display columns, filled by the same pass as 0053.
--
-- 1. summary_zh_public — the hole 0053 left open.
--
-- 0053 stopped publishing title.zh to guests because the translated title
-- carries the source proper noun in full-width parentheses and is therefore a
-- ready-made search key back to the official notice. The summary sitting
-- directly underneath it was not touched, and summary.zh is a faithful
-- translation of the source `objeto` — which in every portal we ingest
-- restates the project name, the municipality and often the street. So the
-- redacted title was published above an unredacted paraphrase of itself, in
-- four places at once: the card, the detail page's 项目摘要 block, the meta
-- description (which is the search-result snippet — read without even opening
-- the page) and the JSON-LD description.
--
-- Read through publicSummaryOf(), which — unlike publicTitleOf — FAILS CLOSED:
-- a row with no generated summary shows the generic placeholder rather than
-- the real one. The title could not do that (it is the <h1> and the <title>;
-- blanking it blanks the page), but the summary block is already conditional,
-- so there is no reason to keep leaking while the backfill runs.
--
-- 2. title_zh_short — a title a human can read in a list.
--
-- Source titles are administrative sentences, and a faithful translation of
-- one is an administrative sentence in Chinese: 「公开招标（电子）第023/2026号
-- ——专业工程公司承建专业社会救助参考中心（CREAS），位于塞乌阿祖尔社区
-- （Bairro Céu Azul）」. That is correct and it is unreadable as a list row.
--
-- Not fixed by changing the translation prompt, for two reasons. The
-- translation is the archival record a subscriber matches against the bid
-- documents, and its rule "carry every reference code through unchanged"
-- exists because those codes are how a bidder finds the procurement at all —
-- a condensing prompt is exactly the kind of thing that quietly drops one.
-- And rewriting title.zh in place would destroy the translation with no undo.
-- So the short form is DERIVED and stored beside it: title.zh stays exactly as
-- translated (still shown on the detail page, still guarded by
-- findDroppedIdentifiers), and clearing this column returns the site to
-- today's behaviour.
--
-- Both are nullable and both are read through a fallback, so they improve rows
-- as they fill rather than gating the site on a backfill.
alter table tenders add column if not exists title_zh_short text;
alter table tenders add column if not exists summary_zh_public text;

comment on column tenders.title_zh_short is
  'Condensed Chinese title for MEMBERS: place, asset, works type and scale, with procurement boilerplate, tender numbers, street addresses, funding-agreement references and "see the attached documents" pointers removed. Keeps the place names and the full-width parentheses that title_zh_public drops — a member is meant to be able to find this procurement. NULL means not generated yet; members fall back to title->>''zh''. Generated by npm run titles:public.';

comment on column tenders.summary_zh_public is
  'De-identified Chinese summary for guests, crawlers and search snippets: what is being procured and at what scale, with place names, agency names, facility names, procurement codes and exact quantities removed. NULL means not generated yet — public surfaces then show the generic placeholder, NOT summary->>''zh'' (fail closed). Members always see summary->>''zh''. Generated by npm run titles:public; never hand-written unless summary_zh_public is also added to manual_field_overrides.';
